-- Jetpack Nano TikTok seed (real public TikTok videos, embedded via official oEmbed)
delete from public.posts; delete from public.users;
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_audiobing','Audiobing','audiobing',551,false,310);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_josieedwardsmusic','Josie Edwards','josieedwardsmusic',4215,false,104);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_itzme_ivan24','Ivan','itzme_ivan24',2367,false,246);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_middaravut','funny video','midda.ravut',3039,true,311);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_y3qgrqvhb0','fail.funny','y3qgrqvhb0',7662,true,205);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_zazasadventuressss','Funniest moments','zazasadventuressss',4290,false,67);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_randomci','⭐️Random⭐️','random.c.i',5871,true,258);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_mallowsarttricks','Mallow','mallows.art.tricks',3295,true,370);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_itsajart','AJstudios','itsajart',7355,false,64);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_recipeincaption','recipeincaption','recipeincaption',4278,false,21);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_thelittlechef74','The Little Chef','the.little.chef74',2370,false,225);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_giovannisiracusaa','Giovanni Siracusa','giovannisiracusaa',4472,false,389);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_katies_wanderlust','Katie Reist 🇨🇦','katies_wanderlust',2940,false,364);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_ashraejack','ash !!','ashraejack',5074,false,70);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_whakkko','WhAkkko','whakkko',1294,false,89);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_shereinabdelhady','shoosh','shereinabdelhady',8338,false,77);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_djthatabguy','Darien “That Ab Guy” Johnson','djthatabguy',7610,true,361);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_caralinerosee','caraline rose','caralinerosee',6265,true,303);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_retrotechlab','RetroTech Lab','retrotechlab',6829,false,353);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_ray_fu','Ray Fu','ray_fu',5431,true,137);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_dumbxtech1','Dumbxtech','dumbxtech1',8632,true,203);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_destinationinspiration','Garrett Sears','destinationinspiration',6343,false,34);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_bradenjstanley','bradenjstanley','bradenjstanley',7589,false,53);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_tomgingergaming','tomgingergaming','tomgingergaming',7829,false,354);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_dmacgames','dmacgames','dmacgames',1521,false,293);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_wilfratgaming','Wilfrat','wilfratgaming',5613,false,204);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_thtgrlreads','Jaimee 🧚‍♂️ 🐉 🩵','thtgrlreads',1558,false,324);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_kenziedeerinreads','kenziedeerinreads 🪩🥀🕯️','kenziedeerinreads',3374,false,146);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_probablyoffreading','miranda 🎀','probablyoffreading',500,false,239);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_sparkleandthread','Marie 🤓','sparkleandthread',4474,false,397);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_nataliasunn','nnataliasun on ig','nataliasunn',8716,false,74);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_millane','millane','millane',4671,false,323);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_thescienceway1','The Science Way','thescienceway1',7604,false,25);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_basicscience37','basic science','basic.science37',1203,false,112);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_scixlab','scixlab','scixlab',1488,true,373);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_the_hayeks','The_hayeks','the_hayeks',1977,false,291);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_1minuteanimals','1 Minute Animals','1minuteanimals',3275,true,389);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_animal_lore','ANIMAL LORE','animal_lore',4385,true,72);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_dreanaylor','AndreaNay100','dreanaylor',5368,true,247);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_happyhome_withsara79','Sara 🪴','happyhome_withsara79',8698,true,378);
insert into public.users (id,name,handle,followers,verified,joined_days_ago) values ('tt_jixiewang','JACKGOLD','jixiewang',1322,false,350);
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t1','tt_audiobing','music','tiktok',null,null,null,'55 Minutes of Bruno Mars Songs (The Playlist for You) 00:00 I Just Might 03:33 Grenade 07:13 Locked Out Of Heaven 11:07 When I Was Your Man 15:02 24K Magic 18:48 Talking To The Moon 22:23 That’s What I Like 25:53 Just The Way You Are 29:50 Treasure 33:02 Leave the Door Open 37:10 It Will Rain 41:37 Finesse (Remix) (feat. Cardi B) 45:20 The Lazy Song 48:39 Marry You 52:26 Smokin Out The Window #brunomars #music #song #playlist #fyp',0,20,4,24,'https://www.tiktok.com/@audiobing/video/7651858835447057672');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t2','tt_josieedwardsmusic','music','tiktok',null,null,null,'It’s been a little over a year of ‘good girls.’ Wow it’s been a wild ride. Thanks for changing my life with this song <3 I’m no longer making lattes but I am writing and working on a lot more music I can’t wait for you to hear :)  #singersongwriter #folkmusic',15000,351,168,35,'https://www.tiktok.com/@josieedwardsmusic/video/7648041195548970253');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t3','tt_itzme_ivan24','music','tiktok',null,null,null,'#music#coversong #coverlagu#anyone #demilovato',650000,14445,7228,11,'https://www.tiktok.com/@itzme_ivan24/video/7650507694234750215');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t4','tt_middaravut','comedy','tiktok',null,null,null,'Pulling a child''s tooth? 🦷 That''s crazy! 😂 #funny #fyp #prank #scary #foryou',0,16,7,27,'https://www.tiktok.com/@midda.ravut/video/7631520786586684702');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t5','tt_y3qgrqvhb0','comedy','tiktok',null,null,null,'Marine animals are cute and funny 🤣🤣 #animals #marine #funny #funnyvideos #Foryou',15000,336,171,25,'https://www.tiktok.com/@y3qgrqvhb0/video/7644143528699907358');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t6','tt_zazasadventuressss','comedy','tiktok',null,null,null,'#tomholland #funny #trynottolaugh #reaction  Tom Holland React Funniest',650000,14445,7233,10,'https://www.tiktok.com/@zazasadventuressss/video/7644975202278886670');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t7','tt_randomci','art','tiktok',null,null,null,'How to make satisfying art process videos  #artprocess #arttips #artaccount #videotips #drawingtips',0,17,4,4,'https://www.tiktok.com/@random.c.i/video/7649810085937433878');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t8','tt_mallowsarttricks','art','tiktok',null,null,null,'break everything down into easy shapes! 😊 here’s a trick to help draw the human torso, shoulders and chest! - mallow #howtodraw #artteacher #arttutorials #arthacks #drawingtips',15000,359,179,23,'https://www.tiktok.com/@mallows.art.tricks/video/7650443710567648534');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t9','tt_itsajart','art','tiktok',null,null,null,'#arttips #drawing #howtodraw #art #ANIME',650000,14469,7222,1,'https://www.tiktok.com/@itsajart/video/7652397045453507853');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t10','tt_recipeincaption','cooking','tiktok',null,null,null,'Crispy Chicken Shawarma Wraps 🔥 For all of you asking about my recipe organizing app, search “Osta” on the app or google play store 🫶 Juicy chicken shawarma, creamy garlic sauce and crispy fries wrapped into one perfect bite 🌯 For the Chicken: -1.5 lbs (680g) skinless chicken thighs, sliced into strips -Seasoning: 1 tbsp paprika, 1 tbsp cumin, 1 tbsp onion powder, 2 tsp coriander, 1 tsp allspice, 2 tsp turmeric, 2 tsp black pepper, 1 tsp salt -3 tbsp olive oil -8 garlic cloves, minced -2 tbsp tomato paste -1/3 cup Greek yogurt -½ lemon, juiced For the Onions: -1 red onion, thinly sliced -2 tbsp olive oil -½ lemon, juiced -1/4 cup fresh parsley, finely chopped -1 tsp salt, 1 tsp black pepper, 2 tsp sumac For the Garlic Sauce: -1/2 cup Greek yogurt -1/2 cup mayonnaise -3 garlic cloves, minced -1/4 lemon, juiced For the Red Sauce Glaze: -1/4 cup olive oil + 2 tbsp tomato paste -1 tbsp pomegranate molasses (optional) -1 tsp paprika For Assembly: -3 Roma tomatoes, diced -Pitas -Frozen french fries Instructions: 1. In a bowl, combine the sliced chicken, spices, olive oil, garlic, tomato paste, yogurt, and lemon juice. Mix well & marinate for as long as your patience can handle, up to overnight. 2. In a large pan over medium-high heat, add a layer of olive oil. Once hot, add the chicken. Cook undisturbed for 3 mins, then cook for 6–7 more mins, stirring often, until golden & cooked through. 3. In a bowl, combine the sliced red onion, olive oil, lemon juice, parsley, salt, pepper, and sumac. Toss well, set aside. 4. In a bowl, mix the Greek yogurt, mayo, garlic, and lemon juice. Set aside in fridge. 5. In a bowl, whisk olive oil, tomato paste, pomegranate molasses (if using), & paprika. 6. Prepare your French fries however you like. Assemble the wraps: spread a generous layer of garlic sauce onto each pita. Top with  chicken, French fries, diced tomatoes & the onions. Wrap tightly. 7. Melt butter in a pan over low heat. Place the wraps seam-side down & brush the tops with the red sauce. Cook until crispy golden, flip, brush the other side, & repeat. Top with more garlic sauce. Enjoy!! #recipesoftiktok #dinnerideas #shawarma #viral #chicken',0,26,2,23,'https://www.tiktok.com/@recipeincaption/video/7645418425090608402');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t11','tt_thelittlechef74','cooking','tiktok',null,null,null,'Cacio e Pepe🇮🇹🧀 Ingredients (Serves 2) • 250g spaghetti or tonnarelli • 120g Pecorino Romano, finely grated • 2 tsp freshly cracked black pepper • Pasta water, reserved Instructions 1. Grate the cheese:     Finely grate the Pecorino Romano.     The finer the cheese, the smoother the sauce. 2. Cook the pasta:     Bring a large pot of salted water to a boil.     Cook the pasta until al dente.     Reserve at least 250ml of pasta water before draining. 3. Make the cheese cream:     Add a small amount of warm pasta water to the Pecorino Romano.     Whisk continuously.     Slowly add more water until you have a smooth, creamy sauce. 4. Toast the pepper:     Add the black pepper to a dry pan over medium heat.     Toast for 30–60 seconds until fragrant. 5. Build the sauce:     Add a splash of pasta water to the pan with the pepper.     Add the cooked pasta and toss well. 6. Combine:     Remove the pan from direct heat.     Add the Pecorino mixture and continue tossing.     Add more pasta water if needed until silky and glossy. 7. Serve:     Finish with extra Pecorino Romano.     Top with freshly cracked black pepper. #cacioepepesauce #cacioepepe #pastarecipes #dinnerideas #easyrecipes',15000,356,174,46,'https://www.tiktok.com/@the.little.chef74/video/7647604235298671894');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t12','tt_giovannisiracusaa','cooking','tiktok',null,null,null,'Crispy XL Pork Chops  🍋 Crispy, golden, and finished with a squeeze of fresh lemon. These breaded pork cutlets are easy to make and perfect for a weeknight dinner. Serve them with a simple salad and you''ve got a meal everyone will love.  Ingredients: Bone-in pork chops Flour Eggs Breadcrumbs Salt Frying oil Fresh lemon Directions: 1. Butterfly the pork chops by cutting them open without separating them completely. Pound them thin until evenly flattened. 2. Dredge each pork chop in flour, then egg, and finally breadcrumbs, pressing so the coating sticks. 3. Fry in hot oil for a few minutes per side until golden brown, crispy, and cooked through. 4. Transfer to a plate and season with salt while still hot. Serve with a squeeze of fresh lemon and a simple side salad. #pork #easyrecipe #fy',650000,14471,7224,30,'https://www.tiktok.com/@giovannisiracusaa/video/7649024510196337951');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t13','tt_katies_wanderlust','nature','tiktok',null,null,null,'just remembering that time I saw a cow take a trip to the vet in switzerland, from a mountain top.😄 #fyp #foryoupage #funny #nature #cow',0,6,7,31,'https://www.tiktok.com/@katies_wanderlust/video/7108933286520474885');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t14','tt_ashraejack','nature','tiktok',null,null,null,'ah such a peaceful & relaxing nature experience 😳😂 #pnw #oregon #pnwlife #pnwwonderland #nature #granolagirl',15000,358,173,7,'https://www.tiktok.com/@ashraejack/video/7106262709355728174');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t15','tt_whakkko','nature','tiktok',null,null,null,'Never caught a catfish this fast. #fish #fishing #fishtok #florida #offshore #boat #bass #bassfishing #amazon #miama #nature #wildlife #peacock #viral',650000,14447,7230,30,'https://www.tiktok.com/@whakkko/video/7105525375354113326');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t16','tt_shereinabdelhady','fitness','tiktok',null,null,null,'there’s alot of emotions in this video 😂 #fyp #gym #fitness',0,16,1,34,'https://www.tiktok.com/@shereinabdelhady/video/7064703044331523375');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t17','tt_djthatabguy','fitness','tiktok',null,null,null,'Training programs on website! #abs #running #fitness #football #superbowl #athlete #workout #workoutmotivation #creative #sprint #fitnessfreak #gym',15000,362,171,1,'https://www.tiktok.com/@djthatabguy/video/7062056437106707759');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t18','tt_caralinerosee','fitness','tiktok',null,null,null,'muscles do not = masculine (fake body) #strongisbeautiful #gymtok #powerlifting #bodybuilding #gym #lifting #gymlife #fitness #girlswholift #fyp',650000,14448,7224,2,'https://www.tiktok.com/@caralinerosee/video/7069503422751362346');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t19','tt_retrotechlab','tech','tiktok',null,null,null,'Wait... this is a PC? A tiny modular computer that can transform from a mini workstation into something much bigger. The design alone is worth a look. #miniPC #tech #gadgets #desksetup #pcsetup',0,27,14,36,'https://www.tiktok.com/@retrotechlab/video/7645501023393549582');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t20','tt_ray_fu','tech','tiktok',null,null,null,'How to build a $80k/month AI Agency with Kimi #ai #tech',15000,341,174,33,'https://www.tiktok.com/@ray_fu/video/7648481184237800734');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t21','tt_dumbxtech1','tech','tiktok',null,null,null,'#tech #techtok #pc #fyp #funny',650000,14462,7234,28,'https://www.tiktok.com/@dumbxtech1/video/7651377452513561864');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t22','tt_destinationinspiration','travel','tiktok',null,null,null,'Why is a weekend trip to Guatemala actually cheap? 🇬🇹🌋 2026 is the year we ALL start traveling more… Because one of the best adventures in the world is only a few hundred dollars and a long weekend away (weekendmaxing)  How to do this weekend trip (1.5 days of PTO): ✈️ Friday: Fly into Guatemala City ➡️ shuttle to Antigua 🥾 Saturday: Hike Acatenango + Fuego with OX Expeditions, camp on the volcano 🌄 Sunday: Sunrise above the clouds ➡️ hike down ➡️ spend the afternoon exploring Antigua Guatemala ✈️ Monday: Fly home Cost Breakdown: Flights: $250+ (found using @Skyscanner) Hostel: $42 (for 2 nights) Hike: $150 (with @oxexpeditions) Food: $35 Shuttle Bus: $40 Would you do this weekend trip? And if so… Where should the next adventure be? 🌍⬇️ #Guatemalatravel #Acatenango #FuegoVolcano #Weekendtrip #placestovisit',0,23,0,21,'https://www.tiktok.com/@destinationinspiration/video/7606390788867575071');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t23','tt_destinationinspiration','travel','tiktok',null,null,null,'Is this one of the most underrated countries in Europe? Or is that an exaggeration?  If you’re looking for a beautiful country in Europe but with fewer crowds, you NEED to add this to your bucket list. 📍 This is Montenegro 🇲🇪  A country in the Balkan region of Europe, Montenegro has something for everyone.  Looking for a seaside getaway? ✅ Maybe you want to go hiking through beautiful mountains? ✅  Want to get lost in historic villages? ✅  Montenegro travel itinerary: - Bay of Kotor - Perast - Rose - Budva - Sveti Stefan - Petrovac - Gusinje - Prokletije National park - Durmitor National Park The best part?  It''s more affordable and less crowded than other European countries like Italy, Croatia, and Greece. Let me know, would you visit Montenegro?? 🇲🇪  #montenegro #montenegro #montenegrotravel #traveltips #placestovisit',15000,357,173,35,'https://www.tiktok.com/@destinationinspiration/video/7554062370125942046');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t24','tt_bradenjstanley','travel','tiktok',null,null,null,'TAG someone you want to do this with! #luxurytravel #traveltok #traveltiktok #train',650000,14448,7227,32,'https://www.tiktok.com/@bradenjstanley/video/7288019576892296454');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t25','tt_tomgingergaming','gaming','tiktok',null,null,null,'going balls speedrun gameplay 695 #tomgingergaming #mobilegames #androidgames #gameplay #satisfyinggames #goingballs',0,5,12,39,'https://www.tiktok.com/@tomgingergaming/video/7639588706948566290');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t26','tt_dmacgames','gaming','tiktok',null,null,null,'Option A or Option B? #gamer #gameroom #videogames',15000,345,167,37,'https://www.tiktok.com/@dmacgames/video/7642091163515653390');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t27','tt_wilfratgaming','gaming','tiktok',null,null,null,'A time-loop extraction shooter where you die, wake up at the start, and do it all again until you loot your way out. Active Matter is shaping up to be one of 2026''s most hyped shooters.  #ActiveMatter #extractionshooter #gamingtiktok #pcgaming',650000,14452,7222,25,'https://www.tiktok.com/@wilfratgaming/video/7652465954131119383');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t28','tt_thtgrlreads','books','tiktok',null,null,null,'I feel like booktok is in its 5 star era and I’m here for it.  Here are the books you don’t want to miss!  #booktokrecs #bookrecs #newbooks #popularbooks #romantasy ballad of falling dragons by Sarah A Parker',0,19,0,11,'https://www.tiktok.com/@thtgrlreads/video/7651315741567847711');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t29','tt_kenziedeerinreads','books','tiktok',null,null,null,'Part 2 of rapid firing through 22 fantasy standalones!!! Be sure to check out part 1 so you have the full list of recs 🧚📖✨ #standalonebooks #fantasybooks #fantasybookrecs #bookrecs #bookrecommendations',15000,347,177,32,'https://www.tiktok.com/@kenziedeerinreads/video/7652011821821349133');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t30','tt_probablyoffreading','books','tiktok',null,null,null,'5 books so addicting I finished reading them in under 24 hours! #romancebooks #popularbooks #bookrecommendations #booktok #fyp',650000,14464,7222,6,'https://www.tiktok.com/@probablyoffreading/video/7644253194570304782');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t31','tt_sparkleandthread','fashion','tiktok',null,null,null,'These beauties are from @boutiquemma and for this bank holiday weekend she has 20% off EVERYTHING.. Use code MAY20 and treat yourself this weekend. ••. Styled with items from my wardrobe. All old but please ask if you want any further details colour drenching, dopamine dressing, striped trousers, statement trousers, bold fashion, over 40 style, midlife fashion, maximalist style, eclectic fashion, colourful outfit, red blazer outfit, how to style stripes, wide leg trousers, fashion over 40, confidence in colour, everyday styling, personal style, outfit inspiration, spring summer fashion, elevated casual, chic style, fashion reel, style inspiration, wearable fashion, playful dressing, classic with a twist, outfit ideas, stylish women over 40, fashion creator, standout style, capsule wardrobe with colour, high street style, mixing colours, denim and heels, relaxed glam, cool girl style, effortless style, real outfit inspiration, trending fashion, outfit styling ideas, vibrant dressing, fashion influencer UK, Shropshire stylist, wear it well, street style inspired, bold prints, red and turquoise outfit, white shirt styling, blazer styling, fashion content creator, women supporting women, feel good fashion, expressive style, outfit repeat, confidence dressing. Style at any age. @Boutiquemma',0,21,9,28,'https://www.tiktok.com/@sparkleandthread/video/7642854476486823190');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t32','tt_nataliasunn','fashion','tiktok',null,null,null,'girls love feminine and chic sets🧘🏻‍♀️ i am girls <3 from @Ghostboy bought at @REBORNE #styleinspo #outfitinspo #ootd #fashion #grwm',15000,349,172,2,'https://www.tiktok.com/@nataliasunn/video/7649054110490299669');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t33','tt_millane','fashion','tiktok',null,null,null,'It all started when I was 8…',650000,14459,7226,5,'https://www.tiktok.com/@millane/video/7642797845468253472');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t34','tt_thescienceway1','science','tiktok',null,null,null,'I cannot break the laws of physics,.#chemistry #physics #laws #maths #science',0,24,1,47,'https://www.tiktok.com/@thescienceway1/video/7649053144948788510');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t35','tt_basicscience37','science','tiktok',null,null,null,'How precise is the cremation technology?#knowledge #science',15000,357,177,26,'https://www.tiktok.com/@basic.science37/video/7644231738679364878');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t36','tt_scixlab','science','tiktok',null,null,null,'The Ocean Is Deeper Than You Can Imagine #anmopaa #deepsea #ocean #marianatrench #challengerdeep #titanic #exploration #sciencefacts #didyouknow #sciencetok',650000,14444,7233,36,'https://www.tiktok.com/@scixlab/video/7630674422600518915');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t37','tt_the_hayeks','pets','tiktok',null,null,null,'It’s bath time! #duck #ducklings #ducksoftiktok #ducks #duckpet',0,27,14,30,'https://www.tiktok.com/@the_hayeks/video/7635350366535601422');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t38','tt_1minuteanimals','pets','tiktok',null,null,null,'Raccoon 🦝 An Inusual Animal To Have As A Pet  #raccoon #raccoons #raccoonlife #raccoonpet #raccoonlove #raccoonsoftiktok',15000,346,166,34,'https://www.tiktok.com/@1minuteanimals/video/7204267357248769285');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t39','tt_animal_lore','pets','tiktok',null,null,null,'Discover Fennec Fox 🦊 a very cute pet #fennecfox #petfennecfox',650000,14447,7233,39,'https://www.tiktok.com/@animal_lore/video/7296853436576927018');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t40','tt_dreanaylor','diy','tiktok',null,null,null,'Don’t mind the mess I was still moving into my new apartment #fyp #diy #summer #BBPlayDate #ShowYourJOWO #FORDfortheBuilders',0,1,5,6,'https://www.tiktok.com/@dreanaylor/video/7094090119195446570');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t41','tt_happyhome_withsara79','diy','tiktok',null,null,null,'Easy, cheap, and sooo cute!! #designonadime #designonabudget #homedecor #diy #pillarstand #happyhome',15000,358,166,5,'https://www.tiktok.com/@happyhome_withsara79/video/7094322616432954670');
insert into public.posts (id,creator_id,topic,kind,image_url,bg_from,bg_to,caption,likes,comments,shares,age_hours,tiktok_url) values ('t42','tt_jixiewang','diy','tiktok',null,null,null,'Broken screws and nuts can be repaired!#life#lifetips#lifetipsshare#diy#fyp',650000,14455,7226,37,'https://www.tiktok.com/@jixiewang/video/7099673155060452654');
