import { writeFile } from 'node:fs/promises';
const UA = 'JetpackNano/1.0 (https://github.com/seanmeverett/jetpacknano; contact: seansmeverett@gmail.com)';
const Q = {
  p2:'ballpoint pen sketch', p3:'ramen noodle soup', p4:'forest hiking trail',
  p6:'soldering iron circuit board', p7:'ocean sea coast', p9:'denim jacket fashion',
  p10:'dog portrait', p11:'wooden shelf', p14:'oil painting artwork', p15:'sourdough bread',
  p19:'folded clothing wardrobe', p20:'bookshelf books', p23:'acoustic guitar',
  p25:'autumn fashion outfit', p26:'web design computer code', p27:'pasta varieties',
  p28:'bathroom renovation tiles', p29:'pasta dish plate', p30:'gym workout exercise',
  p31:'eye drawing art', p32:'smartphone', p33:'Bali Indonesia beach',
  p34:'video game controller', p35:'red carpet evening gown', p36:'ice frozen water',
  p39:'moss forest closeup',
};
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
async function search(q){
  const url='https://commons.wikimedia.org/w/api.php?'+new URLSearchParams({action:'query',generator:'search',gsrsearch:q,gsrnamespace:'6',gsrlimit:'6',prop:'imageinfo',iiprop:'url|mime|extmetadata',iiurlwidth:'1000',format:'json'});
  const r=await fetch(url,{headers:{'User-Agent':UA}}); const j=await r.json();
  const pages=Object.values(j.query?.pages??{}).sort((a,b)=>(a.index??99)-(b.index??99));
  for(const pg of pages){const ii=pg.imageinfo?.[0];if(!ii?.thumburl||/svg|gif/i.test(ii.mime||''))continue;
    return{credit:(ii.extmetadata?.Artist?.value?.replace(/<[^>]+>/g,'').trim()||'Wikimedia Commons contributor'),
           license:(ii.extmetadata?.LicenseShortName?.value||'see source'),
           source:ii.descriptionurl||ii.url};}
  return null;
}
const out={}; let n=0;
for(const id of Object.keys(Q)){
  let c=null;
  for(const q of [Q[id],Q[id].split(' ')[0]]){try{c=await search(q);if(c)break;}catch{}await sleep(250);}
  if(c){out[id]=c;n++;console.log(`${id}: ${c.credit.slice(0,40)} | ${c.license}`);}
  else{out[id]={credit:'Wikimedia Commons',license:'see source',source:'https://commons.wikimedia.org'};console.log(`${id}: (no meta)`);}
  await sleep(200);
}
const code='// AUTO-GENERATED by scripts/fetch-credits.mjs — image attribution (Wikimedia Commons)\n'+
'export const POST_CREDIT: Record<string, { credit: string; license: string; source: string }> = '+JSON.stringify(out,null,2)+';\n';
await writeFile('src/postImageCredits.ts',code);
console.log(`DONE ${n} credits -> src/postImageCredits.ts`);
