import { writeFile } from 'node:fs/promises';

const UA = 'JetpackNano/1.0 (https://github.com/seanmeverett/jetpacknano; contact: seansmeverett@gmail.com)';
const Q = {
  p2:'ballpoint pen sketch', p3:'ramen noodle soup', p4:'forest hiking trail',
  p6:'soldering iron circuit board', p7:'ocean sea coast', p9:'denim jacket fashion',
  p10:'dog portrait', p11:'wooden shelf', p14:'oil painting artwork', p15:'sourdough bread',
  p19:'folded clothing wardrobe', p20:'bookshelf books', p23:'acoustic guitar',
  p25:'autumn fashion outfit', p26:'web design computer code', p27:'pasta varieties',
  p28:'bathroom renovation tiles', p29:'pasta dish plate', p30:'gym workout exercise',
  p31:'eye drawing art', p32:'smartphone', p33:'Bali Indonesia beach',
  p34:'video game controller', p35:'red carpet evening gown', p36:'ice frozen water',
  p39:'moss forest closeup',
};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function searchCommons(query, limit = 6) {
  const url = 'https://commons.wikimedia.org/w/api.php?' + new URLSearchParams({
    action: 'query', generator: 'search', gsrsearch: query, gsrnamespace: '6',
    gsrlimit: String(limit), prop: 'imageinfo', iiprop: 'url|mime|extmetadata',
    iiurlwidth: '1000', format: 'json',
  });
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error('api ' + res.status);
  const json = await res.json();
  const pages = Object.values(json.query?.pages ?? {});
  pages.sort((a, b) => (a.index ?? 99) - (b.index ?? 99));
  for (const pg of pages) {
    const ii = pg.imageinfo?.[0];
    if (!ii?.thumburl) continue;
    // skip svg/gif (not photographic)
    if (/svg|gif/i.test(ii.mime || '')) continue;
    return { thumburl: ii.thumburl, mime: ii.mime, title: pg.title,
      license: ii.extmetadata?.LicenseShortName?.value || 'see source',
      credit: ii.extmetadata?.Artist?.value?.replace(/<[^>]+>/g, '').trim() || '' };
  }
  return null;
}

const map = {};
let ok = 0, fail = 0;
for (const id of Object.keys(Q)) {
  let chosen = null;
  for (const q of [Q[id], Q[id].split(' ')[0]]) {
    try { chosen = await searchCommons(q); if (chosen) break; } catch (e) { /* retry next */ }
    await sleep(300);
  }
  if (!chosen) { console.log(`FAIL ${id} (${Q[id]}) -> keeping svg`); map[id] = `/posts/${id}.svg`; fail++; continue; }
  const m = chosen.thumburl.match(/\.(jpe?g|png)$/i); const ext = m ? m[1].toLowerCase().replace('jpeg', 'jpg') : 'jpg';
  try {
    const r = await fetch(chosen.thumburl, { headers: { 'User-Agent': UA } });
    if (!r.ok) throw new Error('img ' + r.status);
    const buf = Buffer.from(await r.arrayBuffer());
    await writeFile(`public/posts/${id}.${ext}`, buf);
    map[id] = `/posts/${id}.${ext}`;
    console.log(`OK   ${id} (${Q[id]}) -> ${id}.${ext}  [${chosen.license}]`);
    ok++;
  } catch (e) {
    console.log(`DLFAIL ${id} (${Q[id]}) -> svg (${e.message})`);
    map[id] = `/posts/${id}.svg`; fail++;
  }
  await sleep(250);
}

const code = '// AUTO-GENERATED by scripts/fetch-images.mjs — mapping of image post id -> locally served photo\n' +
  '// Images from Wikimedia Commons (CC / public domain). Re-run the script to refresh.\n' +
  `export const POST_IMAGE: Record<string, string> = ${JSON.stringify(map, null, 2)};\n`;
await writeFile('src/postImages.ts', code);
console.log(`\nDONE: ${ok} photos, ${fail} fallback(s). map -> src/postImages.ts`);
