// AUTO-GENERATED by scripts/fetch-gifs.mjs
export const POST_CREDIT: Record<string, { credit: string; license: string; source: string }> = {
  "p2": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=3593683",
    "credit": "Malter",
    "license": "by-sa 3.0"
  },
  "p4": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=77230089",
    "credit": "European Space Agency",
    "license": "by-sa 3.0"
  },
  "p6": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=89094985",
    "credit": "Glosome",
    "license": "by-sa 4.0"
  },
  "p7": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=82570627",
    "credit": "Yizhengillustration",
    "license": "by-sa 4.0"
  },
  "p9": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=98831484",
    "credit": "Illustrated by Jasmina El Bouamraoui and Karabo Poppy Moletsane. Animators: Kunal Sen & Tisha Pillai.",
    "license": "cc0 1.0"
  },
  "p10": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=48505820",
    "credit": "Craybabes",
    "license": "by-sa 4.0"
  },
  "p11": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=19184328",
    "credit": "Penyulap",
    "license": "by-sa 3.0"
  },
  "p14": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=1169327",
    "credit": "Juraj Simlovic",
    "license": "by-sa 3.0"
  },
  "p19": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=98831484",
    "credit": "Illustrated by Jasmina El Bouamraoui and Karabo Poppy Moletsane. Animators: Kunal Sen & Tisha Pillai.",
    "license": "cc0 1.0"
  },
  "p20": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=3717500",
    "credit": "DemonDeLuxe (Dominique Toussaint)",
    "license": "by-sa 3.0"
  },
  "p23": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=57713146",
    "credit": "NicholasPG",
    "license": "by-sa 4.0"
  },
  "p25": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=155312945",
    "credit": "Wikimedia Foundation",
    "license": "by-sa 4.0"
  },
  "p27": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=88428296",
    "credit": "File:Fermi–Pasta–Ulam–Tsingou recurrence.gif: Jacopo Bertolotti derivative work: Bürgerentscheid",
    "license": "cc0 1.0"
  },
  "p28": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=24091054",
    "credit": "Escapists606",
    "license": "by-sa 3.0"
  },
  "p30": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=67076719",
    "credit": "VideoPlasty",
    "license": "by-sa 4.0"
  },
  "p31": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=179323596",
    "credit": "Wikimedia Foundation staff and contractors",
    "license": "by 4.0"
  },
  "p32": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=173628997",
    "credit": "Wikimedia Foundation staff and contractors",
    "license": "by-sa 4.0"
  },
  "p33": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=112630478",
    "credit": "Rollcloud",
    "license": "by 2.5"
  },
  "p34": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=2160509",
    "credit": "Karophyr at English Wikipedia",
    "license": "by-sa 3.0"
  },
  "p35": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=98821388",
    "credit": "Illustrated by Jasmina El Bouamraoui and Karabo Poppy Moletsane. Animators: Kunal Sen & Tisha Pillai.",
    "license": "cc0 1.0"
  },
  "p36": {
    "source": "https://commons.wikimedia.org/w/index.php?curid=15608062",
    "credit": "AtomicRED",
    "license": "by-sa 3.0"
  }
};
