// AUTO-GENERATED by scripts/fetch-credits.mjs (jpg fallback credits) — image attribution (Wikimedia Commons)
export const POST_CREDIT: Record<string, { credit: string; license: string; source: string }> = {
  "p2": {
    "credit": "Guy MOLL from Faro, Portugal",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Croquis-_Colmar_-_France_(6347452075).jpg"
  },
  "p3": {
    "credit": "Vyacheslav Argenberg",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Japanese_Ramen_Noodle_Soup,_Bangkok,_Thailand.jpg"
  },
  "p4": {
    "credit": "W.carter",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Intertwined_roots_of_two_birches_next_to_Myrstigen_hiking_trail_in_Brastad.jpg"
  },
  "p6": {
    "credit": "U.S. Navy photo by Mass Communication Specialist Seaman John Wagner",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:US_Navy_070129-N-3038W-059_Electronics_Technician_3rd_Class_Christopher_Ralph_uses_a_soldering_iron_to_make_repairs_on_a_circuit_board_in_the_micro-miniature_electronics_repair_shop_aboard_the_Nimitz-class_aircraft_carrier_USS.jpg"
  },
  "p7": {
    "credit": "Dietmar Rabich",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sydney_(AU),_Coast,_Australian_Fur_Seals_--_2019_--_3489.jpg"
  },
  "p9": {
    "credit": "Staff photographer for the Rhode Island School of Design Museum of Art",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:2002_Junya_Watanabe_for_Comme_des_Gar%C3%A7ons_jacket,_blue_denim_jeans_patchwork_02.jpg"
  },
  "p10": {
    "credit": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Human%E2%80%93canine_friendship_-_girl_hugging_her_dog_tightly_at_golden_hour_in_Laos.jpg"
  },
  "p11": {
    "credit": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Illuminated_wooden_shelf_with_many_glass_jars_containing_cookies_for_sale_in_Tokyo.jpg"
  },
  "p14": {
    "credit": "Valentine Manchon Duchesne",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Oval_portrait_miniature_of_girl_oil_painting_by_Valentine_Manchon_Duchesne_-_with_scale.jpg"
  },
  "p15": {
    "credit": "Tomascastelazo",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Home_made_sour_dough_bread.jpg"
  },
  "p19": {
    "credit": "Reed, Ruth Stevens",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Efficiency_in_clothing_(IA_efficiencyinclot00reed).pdf"
  },
  "p20": {
    "credit": "Roman Eisele",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Part_of_a_bookshelf_containing_books_by_ancient_philosophers_(1.1).jpg"
  },
  "p23": {
    "credit": "Wilfredor",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Man_playing_an_acoustic_brazilian_guitar_(Viol%C3%A3o)_on_Marco_Zero_Square,_Refice,_Pernambuco,_Brazil.jpg"
  },
  "p25": {
    "credit": "Seppo Konstig",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Autumn_fashion_on_butik_owners_1993_(JOKASEK5D05C-1).tif"
  },
  "p26": {
    "credit": "Creator:Jeremy Keith",
    "license": "CC BY 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Jeremy_Keith_-_Resilient_Web_Design_(portrait).pdf"
  },
  "p27": {
    "credit": "Popo le Chien",
    "license": "CC BY-SA 3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Macaronis.jpeg"
  },
  "p28": {
    "credit": "Smtzzz",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bathroom_splash_back.jpg"
  },
  "p29": {
    "credit": "Breville USA",
    "license": "CC BY 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Meaty_Lasagna_8of8_(8736299782).jpg"
  },
  "p30": {
    "credit": "Samson Ssemakadde",
    "license": "CC0",
    "source": "https://commons.wikimedia.org/wiki/File:Gym_workout_machine.jpg"
  },
  "p31": {
    "credit": "Pieter Brueghel the Elder",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg"
  },
  "p32": {
    "credit": "AnVuong1222004",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Nokia_6630.png"
  },
  "p33": {
    "credit": "Jakub Hałun",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Sunset,_Kuta,_Bali,_Indonesia,_20220825_1755_0879.jpg"
  },
  "p34": {
    "credit": "Evan-Amos",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Xbox-360-Wireless-Controller-White.jpg"
  },
  "p35": {
    "credit": "Eva Rinaldi",
    "license": "CC BY-SA 2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Bree_Robertson_presents_a_red_carpet_gown.jpg"
  },
  "p36": {
    "credit": "Andreas Tille",
    "license": "CC BY-SA 4.0",
    "source": "https://commons.wikimedia.org/wiki/File:IceBlockNearJoekullsarlon.jpg"
  },
  "p39": {
    "credit": "Forest Service - Northern Region",
    "license": "Public domain",
    "source": "https://commons.wikimedia.org/wiki/File:Moss_Capsules,_closeup_(46944415604).jpg"
  }
};
